
// i18n & RTL
const qs = s => document.querySelector(s);
const qsa = s => Array.from(document.querySelectorAll(s));

const I = {
  en:{navHome:'Home',navAbout:'About',navServices:'Services',navProjects:'Projects',navContact:'Contact',ctaQuote:'Get Quote',heroH1:'Transform Your Ideas Into Reality',heroLead:'Professional 3D printing services for prototypes, custom parts, and innovative designs across all industries',statProjects:'Projects Completed',statSatisfaction:'Client Satisfaction',statResponse:'Response Time',ctaViewWork:'View Our Work',ctaStart:'Start Your Project',svcH2:'Professional 3D Printing Services',svcLead:'From concept to creation, we bring your ideas to life with precision and quality',svcCAD:'3D Design & Modeling',svcPrint:'3D Printing',svcPost:'Post-Processing',svcConsult:'Consultation',featH2:'Featured Projects',featLead:'Explore our prototypes across three main categories.',decoration:'Decoration',phoneAccessories:'Phone Accessories',rareSpareParts:'Rare Spare Parts',decDesc:'Art pieces, signage, desk toys, thematic displays.',phoneDesc:'Cases, mounts, stands, cable organizers.',spareDesc:'Hard-to-find replacements, legacy model parts.',ctaGetStarted:'Get Started Today',aboutH2:'About Proto‑Maker',aboutLead:'Transforming ideas into tangible reality through innovative 3D printing technology.',contactH2:'Get In Touch',contactLead:"Ready to bring your ideas to life? Let's discuss your project",labelName:'Full Name *',labelEmail:'Email Address *',labelType:'Project Type',labelMessage:'Project Description *',labelFile:'Reference File (Optional)',sendMsg:'Send Message',useMail:'Use mail app',whyUs:'Why Choose Us',footerTag:'Bringing ideas to life through 3D innovation',footerLinks:'Quick Links',footerContact:'Contact & Social',rights:'All rights reserved.',chooseLang:'Choose Language'},
  fr:{navHome:'Accueil',navAbout:'À propos',navServices:'Services',navProjects:'Projets',navContact:'Contact',ctaQuote:'Devis',heroH1:'Transformez vos idées en réalité',heroLead:"Services d’impression 3D pour prototypes, pièces sur mesure et conceptions innovantes tous secteurs",statProjects:'Projets réalisés',statSatisfaction:'Satisfaction client',statResponse:'Délai de réponse',ctaViewWork:'Voir nos travaux',ctaStart:'Lancer votre projet',svcH2:"Services d’impression 3D",svcLead:'Du concept à la réalisation, avec précision et qualité',svcCAD:'Conception & Modélisation 3D',svcPrint:'Impression 3D',svcPost:'Finition',svcConsult:'Conseil',featH2:'Projets à la une',featLead:'Découvrez nos prototypes répartis en trois catégories.',decoration:'Décoration',phoneAccessories:'Accessoires Téléphone',rareSpareParts:'Pièces détachées rares',decDesc:'Œuvres, signalétique, jouets de bureau, décors thématiques.',phoneDesc:'Coques, supports, stations, organiseurs.',spareDesc:'Remplacements introuvables, pièces pour anciens modèles.',ctaGetStarted:"Commencer aujourd'hui",aboutH2:'À propos de Proto‑Maker',aboutLead:"Transformer les idées en réalité grâce à l'impression 3D.",contactH2:'Contactez‑nous',contactLead:'Discutons de votre projet',labelName:'Nom complet *',labelEmail:'E‑mail *',labelType:'Type de projet',labelMessage:'Description du projet *',labelFile:'Fichier de référence (optionnel)',sendMsg:'Envoyer',useMail:"Ouvrir l’e‑mail",whyUs:'Pourquoi nous choisir',footerTag:"Donner vie aux idées par l'innovation 3D",footerLinks:'Liens rapides',footerContact:'Contact & Réseaux',rights:'Tous droits réservés.',chooseLang:'Choisir la langue'},
  ar:{navHome:'الرئيسية',navAbout:'من نحن',navServices:'الخدمات',navProjects:'المشاريع',navContact:'اتصال',ctaQuote:'عرض سعر',heroH1:'حوّل أفكارك إلى واقع',heroLead:'خدمات طباعة ثلاثية الأبعاد للنماذج الأولية والقطع المخصّصة والتصاميم المبتكرة لكل الصناعات',statProjects:'مشروع منجز',statSatisfaction:'رضا العملاء',statResponse:'زمن الرد',ctaViewWork:'شاهد أعمالنا',ctaStart:'ابدأ مشروعك',svcH2:'خدمات الطباعة ثلاثية الأبعاد',svcLead:'من الفكرة إلى التصنيع بدقة وجودة',svcCAD:'تصميم ونمذجة ثلاثية الأبعاد',svcPrint:'الطباعة ثلاثية الأبعاد',svcPost:'تشطيب',svcConsult:'استشارة',featH2:'أعمال مميزة',featLead:'استكشف نماذجنا عبر ثلاث فئات رئيسية.',decoration:'الديكور',phoneAccessories:'ملحقات الهاتف',rareSpareParts:'قطع غيار نادرة',decDesc:'أعمال فنية ولافتات ومجسّمات مكتبية وعروض.',phoneDesc:'أغطية وحوامل وقواعد ومنظّمات كابلات.',spareDesc:'بدائل يصعب العثور عليها لنماذج قديمة.',ctaGetStarted:'ابدأ الآن',aboutH2:'عن Proto‑Maker',aboutLead:'نحوّل الأفكار إلى واقع بتقنية الطباعة ثلاثية الأبعاد.',contactH2:'تواصل معنا',contactLead:'لنناقش مشروعك',labelName:'الاسم الكامل *',labelEmail:'البريد الإلكتروني *',labelType:'نوع المشروع',labelMessage:'وصف المشروع *',labelFile:'ملف مرجعي (اختياري)',sendMsg:'إرسال',useMail:'فتح البريد',whyUs:'لماذا نحن',footerTag:'نمنح الحياة للأفكار بالابتكار',footerLinks:'روابط سريعة',footerContact:'التواصل ووسائل التواصل',rights:'جميع الحقوق محفوظة',chooseLang:'اختر اللغة'}
};

function applyLang(l){
  const d = I[l] || I.en;
  document.documentElement.lang = l;
  document.documentElement.dir = (l === 'ar') ? 'rtl' : 'ltr';
  qsa('[data-i18n]').forEach(el => { const k = el.getAttribute('data-i18n'); if (d[k]) el.textContent = d[k]; });
  localStorage.setItem('pm_lang', l);
  const btn = qs('#open-lang'); if (btn) btn.textContent = l.toUpperCase();
}
applyLang(localStorage.getItem('pm_lang') || 'en');
